import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Footer from '@/component/footer';
const poppinsFont = Poppins({
  weight: '500',
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Home 2 – Youtube Video – Grand Tour | Booking Travel WordPress',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={poppinsFont.className} style={{ margin: 0 }}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
